server:
  port: 8888
spring:
  datasource:
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.school.demo.bo
  mapper-locations: classpath:mapper-gen/*.xml
